"""BiGRU temporal model trainer.

Self-supervised: predicts next-window autoencoder anomaly score.
Labels are generated by running the autoencoder on each window and computing
reconstruction error → anomaly score.

Uses GroupShuffleSplit(groups=attacker_mac) to prevent data leakage across
train/val splits.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

from app.config import settings
from app.models.bigru import ThreatBiGRU

logger = logging.getLogger(__name__)

FEATURE_DIM = 12


def load_sequences_from_csv(
    csv_path: str, max_seq_len: int
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Load pre-built sequences from CSV.

    Expected CSV columns: attacker_mac, then max_seq_len * 12 feature values,
    then max_seq_len anomaly scores (labels).

    For simplicity, this loader expects a numpy-saved .npz file with keys:
    - sequences: (N, max_seq_len, 12) float32
    - masks: (N, max_seq_len) float32
    - labels: (N,) float32  — next-window anomaly score
    - groups: (N,) — group identifier (attacker MAC hash) for split
    """
    data = np.load(csv_path)
    return data["sequences"], data["masks"], data["labels"], data["groups"]


def build_sequences_from_features(
    features_by_attacker: dict[str, List[np.ndarray]],
    ae_scores_by_attacker: dict[str, List[float]],
    max_seq_len: int,
    min_seq_len: int = 4,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Build training sequences from per-attacker feature history.

    For each attacker with N windows, generates (N - min_seq_len) training
    samples using sliding windows of length [min_seq_len, max_seq_len].
    Label = anomaly score of the window AFTER the sequence end.
    """
    all_seqs: List[np.ndarray] = []
    all_masks: List[np.ndarray] = []
    all_labels: List[float] = []
    all_groups: List[int] = []

    for attacker, feats in features_by_attacker.items():
        scores = ae_scores_by_attacker[attacker]
        n = len(feats)
        if n <= min_seq_len:
            continue

        group_id = hash(attacker) & 0xFFFFFFFF

        for end_idx in range(min_seq_len, n):
            start_idx = max(0, end_idx - max_seq_len)
            seq_feats = feats[start_idx:end_idx]
            seq_len = len(seq_feats)

            padded = np.zeros((max_seq_len, FEATURE_DIM), dtype=np.float32)
            padded[:seq_len] = np.stack(seq_feats)

            mask = np.zeros(max_seq_len, dtype=np.float32)
            mask[:seq_len] = 1.0

            label = scores[end_idx]

            all_seqs.append(padded)
            all_masks.append(mask)
            all_labels.append(label)
            all_groups.append(group_id)

    return (
        np.stack(all_seqs),
        np.stack(all_masks),
        np.array(all_labels, dtype=np.float32),
        np.array(all_groups, dtype=np.int64),
    )


def train_bigru(
    sequences: np.ndarray,
    masks: np.ndarray,
    labels: np.ndarray,
    groups: np.ndarray,
    hidden_size: int = 64,
    num_layers: int = 2,
    dropout: float = 0.3,
    epochs: int = 50,
    batch_size: int = 32,
    lr: float = 1e-3,
    val_fraction: float = 0.2,
) -> ThreatBiGRU:
    from sklearn.model_selection import GroupShuffleSplit

    model = ThreatBiGRU(
        input_dim=FEATURE_DIM,
        hidden_size=hidden_size,
        num_layers=num_layers,
        dropout=dropout,
    )

    splitter = GroupShuffleSplit(n_splits=1, test_size=val_fraction, random_state=42)
    train_idx, val_idx = next(splitter.split(sequences, labels, groups))

    train_seqs = torch.tensor(sequences[train_idx], dtype=torch.float32)
    train_masks = torch.tensor(masks[train_idx], dtype=torch.float32)
    train_labels = torch.tensor(labels[train_idx], dtype=torch.float32).unsqueeze(1)

    val_seqs = torch.tensor(sequences[val_idx], dtype=torch.float32)
    val_masks = torch.tensor(masks[val_idx], dtype=torch.float32)
    val_labels = torch.tensor(labels[val_idx], dtype=torch.float32).unsqueeze(1)

    train_loader = DataLoader(
        TensorDataset(train_seqs, train_masks, train_labels),
        batch_size=batch_size,
        shuffle=True,
    )

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.MSELoss()

    best_val_loss = float("inf")
    best_state = None
    patience = 10
    patience_counter = 0

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        for batch_seq, batch_mask, batch_label in train_loader:
            optimizer.zero_grad()
            pred, _ = model(batch_seq, batch_mask)
            loss = criterion(pred, batch_label)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            epoch_loss += loss.item() * batch_seq.size(0)

        model.eval()
        with torch.no_grad():
            val_pred, _ = model(val_seqs, val_masks)
            val_loss = criterion(val_pred, val_labels).item()

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = {k: v.clone() for k, v in model.state_dict().items()}
            patience_counter = 0
        else:
            patience_counter += 1

        if (epoch + 1) % 10 == 0:
            logger.info(
                "Epoch %d/%d — train_loss=%.6f, val_loss=%.6f",
                epoch + 1, epochs, epoch_loss / len(train_idx), val_loss,
            )

        if patience_counter >= patience:
            logger.info("Early stopping at epoch %d", epoch + 1)
            break

    if best_state is not None:
        model.load_state_dict(best_state)
    model.eval()
    return model


def export_bigru_onnx(model: ThreatBiGRU, output_path: Path, max_seq_len: int) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    model.eval()

    sample_x = torch.randn(1, max_seq_len, FEATURE_DIM, dtype=torch.float32)
    sample_mask = torch.ones(1, max_seq_len, dtype=torch.float32)

    torch.onnx.export(
        model,
        (sample_x, sample_mask),
        str(output_path),
        input_names=["features", "mask"],
        output_names=["prediction", "attention_weights"],
        dynamic_axes={
            "features": {0: "batch", 1: "seq_len"},
            "mask": {0: "batch", 1: "seq_len"},
            "prediction": {0: "batch"},
            "attention_weights": {0: "batch", 1: "seq_len"},
        },
        opset_version=17,
    )
    logger.info("Exported BiGRU ONNX model to %s", output_path)


def run_training(
    tier: int,
    npz_path: str,
    epochs: int,
    model_dir: str,
    hidden_size: int = 64,
    num_layers: int = 2,
    dropout: float = 0.3,
) -> Path:
    max_seq_lens = {1: 32, 2: 32, 3: 48}
    max_seq_len = max_seq_lens.get(tier, 32)

    sequences, masks, labels, groups = load_sequences_from_csv(npz_path, max_seq_len)
    logger.info("Loaded %d training sequences for tier %d", len(sequences), tier)

    if len(sequences) < 20:
        raise ValueError(f"Not enough training data: {len(sequences)} sequences (need >= 20)")

    model = train_bigru(
        sequences=sequences,
        masks=masks,
        labels=labels,
        groups=groups,
        hidden_size=hidden_size,
        num_layers=num_layers,
        dropout=dropout,
        epochs=epochs,
    )

    out_path = Path(model_dir) / f"bigru_v1_tier{tier}.onnx"
    export_bigru_onnx(model, out_path, max_seq_len)
    return out_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train BiGRU temporal threat model")
    parser.add_argument("--tier", type=int, required=True, choices=[1, 2, 3])
    parser.add_argument("--npz", type=str, required=True, help="Path to .npz training data")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--hidden-size", type=int, default=64)
    parser.add_argument("--num-layers", type=int, default=2)
    parser.add_argument("--dropout", type=float, default=0.3)
    parser.add_argument("--model-dir", type=str, default=settings.model_dir)
    return parser.parse_args()


def main() -> None:
    logging.basicConfig(level=logging.INFO)
    args = parse_args()
    output = run_training(
        tier=args.tier,
        npz_path=args.npz,
        epochs=args.epochs,
        model_dir=args.model_dir,
        hidden_size=args.hidden_size,
        num_layers=args.num_layers,
        dropout=args.dropout,
    )
    print(str(output))


if __name__ == "__main__":
    main()
