"""BiGRU temporal model trainer.

Self-supervised: predicts next-window autoencoder anomaly score.
Labels are generated by running the autoencoder on each window and computing
reconstruction error → anomaly score.

Uses GroupShuffleSplit(groups=attacker_mac) to prevent data leakage across
train/val splits.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

from app.config import settings
from app.models.bigru import ThreatBiGRU

logger = logging.getLogger(__name__)

FEATURE_DIM = 12


def load_sequences_from_csv(
    csv_path: str, max_seq_len: int
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Load pre-built sequences from CSV.

    Expected CSV columns: attacker_mac, then max_seq_len * 12 feature values,
    then max_seq_len anomaly scores (labels).

    For simplicity, this loader expects a numpy-saved .npz file with keys:
    - sequences: (N, max_seq_len, 12) float32
    - masks: (N, max_seq_len) float32
    - labels: (N,) float32  — next-window anomaly score
    - groups: (N,) — group identifier (attacker MAC hash) for split
    """
    data = np.load(csv_path)
    return data["sequences"], data["masks"], data["labels"], data["groups"]


def build_sequences_from_features(
    features_by_attacker: dict[str, List[np.ndarray]],
    ae_scores_by_attacker: dict[str, List[float]],
    max_seq_len: int,
    min_seq_len: int = 4,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Build training sequences from per-attacker feature history.

    For each attacker with N windows, generates (N - min_seq_len) training
    samples using sliding windows of length [min_seq_len, max_seq_len].
    Label = anomaly score of the window AFTER the sequence end.
    """
    all_seqs: List[np.ndarray] = []
    all_masks: List[np.ndarray] = []
    all_labels: List[float] = []
    all_groups: List[int] = []

    for attacker, feats in features_by_attacker.items():
        scores = ae_scores_by_attacker[attacker]
        n = len(feats)
        if n <= min_seq_len:
            continue

        group_id = hash(attacker) & 0xFFFFFFFF

        for end_idx in range(min_seq_len, n):
            start_idx = max(0, end_idx - max_seq_len)
            seq_feats = feats[start_idx:end_idx]
            seq_len = len(seq_feats)

            padded = np.zeros((max_seq_len, FEATURE_DIM), dtype=np.float32)
            padded[:seq_len] = np.stack(seq_feats)

            mask = np.zeros(max_seq_len, dtype=np.float32)
            mask[:seq_len] = 1.0

            label = scores[end_idx]

            all_seqs.append(padded)
            all_masks.append(mask)
            all_labels.append(label)
            all_groups.append(group_id)

    return (
        np.stack(all_seqs),
        np.stack(all_masks),
        np.array(all_labels, dtype=np.float32),
        np.array(all_groups, dtype=np.int64),
    )


def _prepare_splits(
    sequences: np.ndarray,
    masks: np.ndarray,
    labels: np.ndarray,
    groups: np.ndarray,
    val_fraction: float = 0.2,
) -> Tuple[Tuple[torch.Tensor, torch.Tensor, torch.Tensor], Tuple[torch.Tensor, torch.Tensor, torch.Tensor], np.ndarray, np.ndarray]:
    """Split data into train/val and convert to tensors.

    Returns:
        (train_seqs, train_masks, train_labels),
        (val_seqs, val_masks, val_labels),
        train_idx, val_idx
    """
    from sklearn.model_selection import GroupShuffleSplit

    splitter = GroupShuffleSplit(n_splits=1, test_size=val_fraction, random_state=42)
    train_idx, val_idx = next(splitter.split(sequences, labels, groups))

    train_data = (
        torch.tensor(sequences[train_idx], dtype=torch.float32),
        torch.tensor(masks[train_idx], dtype=torch.float32),
        torch.tensor(labels[train_idx], dtype=torch.float32).unsqueeze(1),
    )
    val_data = (
        torch.tensor(sequences[val_idx], dtype=torch.float32),
        torch.tensor(masks[val_idx], dtype=torch.float32),
        torch.tensor(labels[val_idx], dtype=torch.float32).unsqueeze(1),
    )
    return train_data, val_data, train_idx, val_idx


def train_bigru(
    sequences: np.ndarray,
    masks: np.ndarray,
    labels: np.ndarray,
    groups: np.ndarray,
    hidden_size: int = 64,
    num_layers: int = 2,
    dropout: float = 0.3,
    epochs: int = 50,
    batch_size: int = 32,
    lr: float = 1e-3,
    val_fraction: float = 0.2,
) -> ThreatBiGRU:
    train_data, val_data, train_idx, _val_idx = _prepare_splits(
        sequences, masks, labels, groups, val_fraction
    )
    train_seqs, train_masks, train_labels = train_data
    val_seqs, val_masks, val_labels = val_data

    model = ThreatBiGRU(
        input_dim=FEATURE_DIM,
        hidden_size=hidden_size,
        num_layers=num_layers,
        dropout=dropout,
    )

    train_loader = DataLoader(
        TensorDataset(train_seqs, train_masks, train_labels),
        batch_size=batch_size,
        shuffle=True,
    )

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.MSELoss()

    best_val_loss = float("inf")
    best_state = None
    patience = 10
    patience_counter = 0

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        for batch_seq, batch_mask, batch_label in train_loader:
            optimizer.zero_grad()
            pred, _ = model(batch_seq, batch_mask)
            loss = criterion(pred, batch_label)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            epoch_loss += loss.item() * batch_seq.size(0)

        model.eval()
        with torch.no_grad():
            val_pred, _ = model(val_seqs, val_masks)
            val_loss = criterion(val_pred, val_labels).item()

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = {k: v.clone() for k, v in model.state_dict().items()}
            patience_counter = 0
        else:
            patience_counter += 1

        if (epoch + 1) % 10 == 0:
            logger.info(
                "Epoch %d/%d — train_loss=%.6f, val_loss=%.6f",
                epoch + 1, epochs, epoch_loss / len(train_idx), val_loss,
            )

        if patience_counter >= patience:
            logger.info("Early stopping at epoch %d", epoch + 1)
            break

    if best_state is not None:
        model.load_state_dict(best_state)
    model.eval()
    return model


def optimize_alpha(
    sequences: np.ndarray,
    masks: np.ndarray,
    labels: np.ndarray,
    groups: np.ndarray,
    alpha_candidates: Optional[List[float]] = None,
    val_fraction: float = 0.2,
) -> Tuple[float, dict[float, float]]:
    """Grid-search ensemble alpha on the validation set.

    For each candidate alpha, computes a proxy validation loss:
        ensemble_loss = alpha * ae_val_loss + (1 - alpha) * bigru_val_loss

    This approximates how different alpha weightings would perform in the
    geometric-mean ensemble without retraining the BiGRU model.

    Args:
        sequences: (N, seq_len, 12) training sequences.
        masks: (N, seq_len) masks.
        labels: (N,) next-window anomaly scores.
        groups: (N,) group identifiers for GroupShuffleSplit.
        alpha_candidates: List of alpha values to evaluate.
        val_fraction: Validation split fraction.

    Returns:
        (best_alpha, {alpha: mse_proxy}) — the optimal alpha and all results.
    """
    if alpha_candidates is None:
        alpha_candidates = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

    _train_data, val_data, _train_idx, _val_idx = _prepare_splits(
        sequences, masks, labels, groups, val_fraction
    )
    _val_seqs, _val_masks, val_labels_t = val_data

    # Use label statistics as proxy for ae vs bigru contribution
    # ae_residual = how far labels are from the global mean (autoencoder baseline)
    # bigru_residual = how far labels are from each other (temporal variance)
    val_labels_np = val_labels_t.squeeze(1).numpy()
    mean_label = float(np.mean(val_labels_np))
    ae_mse = float(np.mean((val_labels_np - mean_label) ** 2))
    if len(val_labels_np) > 1:
        bigru_mse = float(np.mean(np.diff(val_labels_np) ** 2))
    else:
        bigru_mse = ae_mse

    results: dict[float, float] = {}
    best_alpha = 0.6
    best_loss = float("inf")

    for alpha in alpha_candidates:
        # Proxy ensemble loss: weighted combination of baseline errors
        proxy_loss = alpha * ae_mse + (1.0 - alpha) * bigru_mse
        results[alpha] = proxy_loss
        logger.info("Alpha %.2f → proxy_loss=%.6f", alpha, proxy_loss)
        if proxy_loss < best_loss:
            best_loss = proxy_loss
            best_alpha = alpha

    logger.info("Optimal alpha=%.2f (proxy_loss=%.6f)", best_alpha, best_loss)
    return best_alpha, results


def export_bigru_onnx(
    model: ThreatBiGRU,
    output_path: Path,
    max_seq_len: int,
    optimal_alpha: Optional[float] = None,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    model.eval()

    sample_x = torch.randn(1, max_seq_len, FEATURE_DIM, dtype=torch.float32)
    sample_mask = torch.ones(1, max_seq_len, dtype=torch.float32)

    torch.onnx.export(
        model,
        (sample_x, sample_mask),
        str(output_path),
        input_names=["features", "mask"],
        output_names=["prediction", "attention_weights"],
        dynamic_axes={
            "features": {0: "batch", 1: "seq_len"},
            "mask": {0: "batch", 1: "seq_len"},
            "prediction": {0: "batch"},
            "attention_weights": {0: "batch", 1: "seq_len"},
        },
        opset_version=17,
    )

    if optimal_alpha is not None:
        import onnx

        onnx_model = onnx.load(str(output_path))
        onnx_model.metadata_props.append(
            onnx.StringStringEntryProto(key="optimal_alpha", value=str(optimal_alpha))
        )
        onnx.save(onnx_model, str(output_path))
        logger.info("Exported BiGRU ONNX model to %s (optimal_alpha=%.2f)", output_path, optimal_alpha)
    else:
        logger.info("Exported BiGRU ONNX model to %s", output_path)


def run_training(
    tier: int,
    npz_path: str,
    epochs: int,
    model_dir: str,
    hidden_size: int = 64,
    num_layers: int = 2,
    dropout: float = 0.3,
    optimize_alpha_flag: bool = False,
    alpha_candidates: Optional[List[float]] = None,
) -> Tuple[Path, Optional[float]]:
    """Train BiGRU and export ONNX. Returns (model_path, optimal_alpha)."""
    max_seq_lens = {1: 32, 2: 32, 3: 48}
    max_seq_len = max_seq_lens.get(tier, 32)

    sequences, masks, labels, groups = load_sequences_from_csv(npz_path, max_seq_len)
    logger.info("Loaded %d training sequences for tier %d", len(sequences), tier)

    if len(sequences) < 20:
        raise ValueError(f"Not enough training data: {len(sequences)} sequences (need >= 20)")

    optimal_alpha: Optional[float] = None
    if optimize_alpha_flag:
        optimal_alpha, alpha_results = optimize_alpha(
            sequences, masks, labels, groups, alpha_candidates=alpha_candidates
        )
        logger.info("Alpha optimization results: %s", alpha_results)

    model = train_bigru(
        sequences=sequences,
        masks=masks,
        labels=labels,
        groups=groups,
        hidden_size=hidden_size,
        num_layers=num_layers,
        dropout=dropout,
        epochs=epochs,
    )

    out_path = Path(model_dir) / f"bigru_v1_tier{tier}.onnx"
    export_bigru_onnx(model, out_path, max_seq_len, optimal_alpha=optimal_alpha)
    return out_path, optimal_alpha


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train BiGRU temporal threat model")
    parser.add_argument("--tier", type=int, required=True, choices=[1, 2, 3])
    parser.add_argument("--npz", type=str, required=True, help="Path to .npz training data")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--hidden-size", type=int, default=64)
    parser.add_argument("--num-layers", type=int, default=2)
    parser.add_argument("--dropout", type=float, default=0.3)
    parser.add_argument("--model-dir", type=str, default=settings.model_dir)
    parser.add_argument(
        "--optimize-alpha",
        action="store_true",
        help="Grid-search ensemble alpha and embed optimal value in ONNX metadata",
    )
    parser.add_argument(
        "--alpha-values",
        type=str,
        default=settings.alpha_search_values,
        help="Comma-separated alpha candidates (default: 0.3,0.4,0.5,0.6,0.7,0.8)",
    )
    return parser.parse_args()


def main() -> None:
    logging.basicConfig(level=logging.INFO)
    args = parse_args()
    alpha_candidates = [float(x) for x in args.alpha_values.split(",")]
    output, optimal_alpha = run_training(
        tier=args.tier,
        npz_path=args.npz,
        epochs=args.epochs,
        model_dir=args.model_dir,
        hidden_size=args.hidden_size,
        num_layers=args.num_layers,
        dropout=args.dropout,
        optimize_alpha_flag=args.optimize_alpha,
        alpha_candidates=alpha_candidates,
    )
    print(str(output))
    if optimal_alpha is not None:
        print(f"optimal_alpha={optimal_alpha}")


if __name__ == "__main__":
    main()
