apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-processing-jobmanager
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-processing-taskmanager
spec:
  replicas: 3