apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: data-ingestion
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-processing-jobmanager
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 9999
        fsGroup: 9999
      containers:
      - name: flink-jobmanager
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 9999
          capabilities:
            drop:
            - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-processing-taskmanager
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 9999
        fsGroup: 9999
      containers:
      - name: flink-taskmanager
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 9999
          capabilities:
            drop:
            - ALL