apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: threat-detection-base

namespace: threat-detection

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - zookeeper.yaml
  - kafka.yaml
  - kafka-topic-init.yaml
  - logstash.yaml
  - emqx.yaml
  - config-server.yaml
  - data-ingestion.yaml
  - stream-processing.yaml
  - taskmanager.yaml
  - customer-management.yaml
  - threat-assessment.yaml
  - alert-management.yaml
  - api-gateway.yaml

commonLabels:
  app.kubernetes.io/name: threat-detection-system
  app.kubernetes.io/component: base

images:
  - name: threat-detection/data-ingestion
    newTag: latest
  - name: threat-detection/stream-processing
    newTag: "1.0"
  - name: threat-detection/api-gateway
    newTag: latest
  - name: threat-detection/config-server
    newTag: latest

configMapGenerator:
  - name: threat-detection-config
    literals:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - LOG_LEVEL=INFO